# Generated by Django 5.2 on 2025-04-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/default.png', upload_to='images/'),
        ),
    ]
